# github actions: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# setup-node: https://github.com/actions/setup-node

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, feature/*]

jobs:
    macos:
        name: macOS nodejs
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: [12.x]
                vscode-version: [minimum, stable]
        steps:
            - env:
                  NODE_OPTIONS: '--max-old-space-size=8192'
                  VSCODE_TEST_VERSION: ${{ vscode-version }}
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run vscode:prepublish
            - name: Tests
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: npm test
            - name: Code coverage
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              run: bash <(curl -s https://codecov.io/bash) -s .coverage

    windows:
        name: Windows nodejs
        runs-on: windows-2019
        strategy:
            matrix:
                node-version: [12.x]
                vscode-version: [minimum, stable]
        steps:
            - env:
                  NODE_OPTIONS: '--max-old-space-size=8192'
                  VSCODE_TEST_VERSION: ${{ vscode-version }}
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run vscode:prepublish
            - name: Tests
              run: npm test
