# github actions: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# setup-node: https://github.com/actions/setup-node

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, feature/*, mynah-dev]

jobs:
    macos:
        name: test macOS
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [16.x]
                vscode-version: [minimum, stable, insiders]
        env:
            VSCODE_TEST_VERSION: ${{ matrix.vscode-version }}
            NODE_OPTIONS: '--max-old-space-size=8192'
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: Tests
              uses: coactions/setup-xvfb@v1
              with:
                  run: npm test
            - name: Code coverage (Core)
              env:
                  # Unset NODE_OPTIONS because of https://github.com/codecov/uploader/issues/475
                  NODE_OPTIONS: ''
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              uses: codecov/codecov-action@v4
              with:
                  flags: macos-core-unittests
                  verbose: true
                  file: ./coverage/core/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}
            - name: Code coverage (Toolkit)
              env:
                  # Unset NODE_OPTIONS because of https://github.com/codecov/uploader/issues/475
                  NODE_OPTIONS: ''
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              uses: codecov/codecov-action@v4
              with:
                  flags: macos-toolkit-unittests
                  verbose: true
                  file: ./coverage/toolkit/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}
            - name: Code coverage (Amazon Q)
              env:
                  # Unset NODE_OPTIONS because of https://github.com/codecov/uploader/issues/475
                  NODE_OPTIONS: ''
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              uses: codecov/codecov-action@v4
              with:
                  flags: macos-amazonq-unittests
                  verbose: true
                  file: ./coverage/amazonq/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}
            - name: Code coverage (CodeWhisperer)
              env:
                  # Unset NODE_OPTIONS because of https://github.com/codecov/uploader/issues/475
                  NODE_OPTIONS: ''
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              uses: codecov/codecov-action@v4
              with:
                  flags: codewhisperer
                  verbose: true
                  file: ./coverage/core/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}

    web:
        name: test Web
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node-version: [16.x]
                vscode-version: [stable, insiders]
        env:
            VSCODE_TEST_VERSION: ${{ matrix.vscode-version }}
            NODE_OPTIONS: '--max-old-space-size=8192'
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: Tests
              uses: coactions/setup-xvfb@v1
              with:
                  run: npm run testWeb

    windows:
        name: test Windows
        runs-on: windows-2019
        strategy:
            fail-fast: false
            matrix:
                node-version: [16.x]
                vscode-version: [stable, insiders]
        env:
            VSCODE_TEST_VERSION: ${{ matrix.vscode-version }}
            NODE_OPTIONS: '--max-old-space-size=8192'
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: Tests
              run: npm test
            - name: Code coverage
              env:
                  # Unset NODE_OPTIONS because of https://github.com/codecov/uploader/issues/475
                  NODE_OPTIONS: ''
              if: ${{ github.repository == 'aws/aws-toolkit-vscode' && ( github.ref == 'master' || github.event_name == 'pull_request' ) }}
              uses: codecov/codecov-action@v4
              with:
                  flags: windows-unittests
                  verbose: true
                  file: ./coverage/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}

    lint:
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                vscode-version: [stable]
        env:
            NODE_OPTIONS: '--max-old-space-size=8192'
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run testCompile
            - run: npm run lint
